### ISSUE TITLE
Roadmap Section

### ISSUE THREAD

**Issue by ConnectCoincade** [ConnectCoincade/new-boss-cultr#4]
Tasks

- [ ] Develop Desktop Version
- [ ] Develop Tab Version
- [ ] Develop Mobile Version
